import { Course } from "@/types/courses";
import { BarChart2, Code2, HeartPulse, Megaphone, Rocket, Sparkles } from "lucide-react";

export const CATEGORIES = [
  { slug: "computer-programming",  label: "Computer Programming",  icon: Code2,      grad: ["#3b82f6", "#06b6d4"] },
  { slug: "entrepreneurship",       label: "Entrepreneurship",       icon: Rocket,     grad: ["#f59e0b", "#ef4444"] },
  { slug: "srhr",                   label: "SRHR",                   icon: HeartPulse, grad: ["#f43f5e", "#a855f7"] },
  { slug: "marketing",              label: "Marketing",              icon: Megaphone,  grad: ["#8b5cf6", "#ec4899"] },
  { slug: "data-science",           label: "Data Science",           icon: BarChart2,  grad: ["#10b981", "#3b82f6"] },
  { slug: "social-media-branding",  label: "Social Media Branding",  icon: Sparkles,   grad: ["#ec4899", "#f97316"] },
];

// ─── All courses ──────────────────────────────────────────────────────────────
export const ALL_COURSES: Course[] = [
  // Computer Programming
  { id: 1,  title: "Full-Stack Web Development with React & Node.js", instructor: "Alex Murenzi",          avatar: "AM", category: "Computer Programming",  categorySlug: "computer-programming",  level: "Intermediate", duration: "42h 30m", lessons: 128, rating: 4.9, reviews: 3241, enrolled: 18400, price: 49,  tags: ["React","Node.js","MongoDB"],        description: "Build production-ready full-stack apps from scratch. Master REST APIs, authentication, and deployment.", featured: true },
  { id: 2,  title: "Python for Beginners: Zero to Automation",        instructor: "Grace Uwase",            avatar: "GU", category: "Computer Programming",  categorySlug: "computer-programming",  level: "Beginner",     duration: "18h 10m", lessons: 64,  rating: 4.8, reviews: 5102, enrolled: 32100, price: 0,   tags: ["Python","Automation","Scripts"],    description: "Learn Python from the ground up. Write scripts, automate tasks, and build your first programs.", isNew: true },
  { id: 3,  title: "Data Structures & Algorithms in JavaScript",      instructor: "Patrick Nkurunziza",     avatar: "PN", category: "Computer Programming",  categorySlug: "computer-programming",  level: "Advanced",     duration: "28h 00m", lessons: 94,  rating: 4.7, reviews: 1820, enrolled: 9200,  price: 39,  tags: ["DSA","JavaScript","Interviews"],    description: "Master data structures and algorithms with JavaScript. Prepare for coding interviews at top tech companies." },
  { id: 4,  title: "Mobile App Development with Flutter & Dart",       instructor: "Sophie Ingabire",        avatar: "SI", category: "Computer Programming",  categorySlug: "computer-programming",  level: "Intermediate", duration: "24h 45m", lessons: 78,  rating: 4.9, reviews: 2140, enrolled: 14300, price: 59,  tags: ["Flutter","Dart","Mobile"],          description: "Build beautiful cross-platform mobile apps with Flutter. Learn Dart and app deployment to iOS and Android." },
  // Entrepreneurship
  { id: 5,  title: "Launch Your Startup in 90 Days",                  instructor: "Diane Uwimana",          avatar: "DU", category: "Entrepreneurship",       categorySlug: "entrepreneurship",       level: "Beginner",     duration: "16h 00m", lessons: 58,  rating: 4.9, reviews: 4210, enrolled: 29400, price: 0,   tags: ["Startup","MVP","Ideation"],         description: "Go from idea to first paying customer. Learn lean startup methodology and rapid iteration.", featured: true },
  { id: 6,  title: "Fundraising & Pitching to Investors",             instructor: "Eric Nkurunziza",        avatar: "EN", category: "Entrepreneurship",       categorySlug: "entrepreneurship",       level: "Intermediate", duration: "12h 30m", lessons: 44,  rating: 4.8, reviews: 1890, enrolled: 11200, price: 59,  tags: ["Pitch Deck","VC","Funding"],        description: "Build a compelling pitch deck and learn what investors actually look for." },
  { id: 7,  title: "Business Finance for Non-Finance Founders",       instructor: "Aline Ishimwe",          avatar: "AI", category: "Entrepreneurship",       categorySlug: "entrepreneurship",       level: "Beginner",     duration: "10h 20m", lessons: 38,  rating: 4.7, reviews: 2340, enrolled: 14800, price: 0,   tags: ["Finance","Cash Flow","Budgeting"],  description: "Understand P&L, burn rate, unit economics, and make smarter financial decisions." },
  { id: 8,  title: "Advanced Growth Strategy & Product-Market Fit",   instructor: "Bruno Kalisa",           avatar: "BK", category: "Entrepreneurship",       categorySlug: "entrepreneurship",       level: "Advanced",     duration: "18h 45m", lessons: 66,  rating: 4.9, reviews: 890,  enrolled: 5300,  price: 69,  tags: ["PMF","Growth","Strategy"],          description: "Frameworks used by billion-dollar companies to find product-market fit.", isNew: true },
  // SRHR
  { id: 9,  title: "Foundations of Sexual & Reproductive Health",     instructor: "Dr. Amina Mukagihana",   avatar: "AM", category: "SRHR",                   categorySlug: "srhr",                   level: "Beginner",     duration: "10h 30m", lessons: 40,  rating: 4.9, reviews: 3820, enrolled: 22100, price: 0,   tags: ["SRHR","Health","Awareness"],        description: "A comprehensive intro to sexual and reproductive health rights for educators and advocates.", featured: true },
  { id: 10, title: "Gender-Based Violence: Prevention & Response",    instructor: "Marie Claire Ingabire",  avatar: "MC", category: "SRHR",                   categorySlug: "srhr",                   level: "Intermediate", duration: "12h 10m", lessons: 46,  rating: 4.8, reviews: 2100, enrolled: 13400, price: 29,  tags: ["GBV","Prevention","Support"],       description: "Equip yourself with tools to prevent, identify, and respond to gender-based violence." },
  { id: 11, title: "Family Planning Methods: A Clinical Guide",       instructor: "Dr. Samuel Uwizeye",     avatar: "SU", category: "SRHR",                   categorySlug: "srhr",                   level: "Advanced",     duration: "18h 45m", lessons: 68,  rating: 4.9, reviews: 980,  enrolled: 5800,  price: 54,  tags: ["Clinical","Family Planning"],       description: "In-depth clinical training on contraception methods and patient care for health practitioners." },
  // Marketing
  { id: 12, title: "Digital Marketing Masterclass: A–Z",             instructor: "Nina Umutoni",           avatar: "NU", category: "Marketing",              categorySlug: "marketing",              level: "Beginner",     duration: "24h 00m", lessons: 88,  rating: 4.9, reviews: 6420, enrolled: 41200, price: 0,   tags: ["SEO","Ads","Email"],                description: "The complete guide to digital marketing — SEO, paid ads, email, analytics, and CRO.", featured: true },
  { id: 13, title: "Copywriting That Converts",                       instructor: "Stella Nyamwasa",        avatar: "SN", category: "Marketing",              categorySlug: "marketing",              level: "Beginner",     duration: "10h 00m", lessons: 38,  rating: 4.8, reviews: 4100, enrolled: 27800, price: 0,   tags: ["Copywriting","Persuasion","Sales"], description: "Write copy that compels action — landing pages, emails, ads, and social posts." },
  { id: 14, title: "Performance Marketing & Paid Ads",                instructor: "Roger Habimana",         avatar: "RH", category: "Marketing",              categorySlug: "marketing",              level: "Intermediate", duration: "16h 20m", lessons: 60,  rating: 4.7, reviews: 1880, enrolled: 11300, price: 54,  tags: ["Google Ads","Meta Ads","ROAS"],     description: "Maximize ROI with proven paid advertising strategies across Google, Meta, and TikTok." },
  { id: 15, title: "Content Marketing & SEO Growth",                  instructor: "Violette Gasana",        avatar: "VG", category: "Marketing",              categorySlug: "marketing",              level: "Intermediate", duration: "14h 45m", lessons: 54,  rating: 4.9, reviews: 3240, enrolled: 19700, price: 39,  tags: ["SEO","Content","Blogging"],         description: "Build organic traffic that compounds. Master keyword strategy and content distribution.", isNew: true },
  // Data Science
  { id: 16, title: "Python for Data Science & Machine Learning",      instructor: "Dr. Joseph Rurangwa",    avatar: "JR", category: "Data Science",           categorySlug: "data-science",           level: "Beginner",     duration: "30h 00m", lessons: 106, rating: 4.9, reviews: 7820, enrolled: 52400, price: 0,   tags: ["Python","Pandas","ML"],             description: "The most complete data science bootcamp — from Python basics to model deployment.", featured: true },
  { id: 17, title: "SQL & Database Analytics",                        instructor: "Laetitia Nzamwita",      avatar: "LN", category: "Data Science",           categorySlug: "data-science",           level: "Beginner",     duration: "14h 30m", lessons: 52,  rating: 4.8, reviews: 5340, enrolled: 35100, price: 0,   tags: ["SQL","PostgreSQL","Analytics"],     description: "Master SQL from fundamentals to advanced analytics with real datasets." },
  { id: 18, title: "Deep Learning with TensorFlow & Keras",          instructor: "Emmanuel Ndahiro",       avatar: "EN", category: "Data Science",           categorySlug: "data-science",           level: "Advanced",     duration: "26h 00m", lessons: 90,  rating: 4.7, reviews: 2100, enrolled: 12600, price: 59,  tags: ["Deep Learning","TensorFlow"],       description: "Build and deploy deep learning models — CNNs, RNNs, transformers, and production pipelines." },
  // Social Media Branding
  { id: 19, title: "Build Your Personal Brand on Social Media",       instructor: "Chloé Mukazitoni",       avatar: "CM", category: "Social Media Branding",  categorySlug: "social-media-branding",  level: "Beginner",     duration: "12h 00m", lessons: 44,  rating: 4.9, reviews: 8120, enrolled: 56300, price: 0,   tags: ["Personal Brand","Instagram"],       description: "Go from zero to recognizable. Build a consistent brand identity across every platform.", featured: true },
  { id: 20, title: "TikTok & Reels Content Strategy",                 instructor: "Manzi Uwase",            avatar: "MU", category: "Social Media Branding",  categorySlug: "social-media-branding",  level: "Beginner",     duration: "8h 30m",  lessons: 34,  rating: 4.9, reviews: 6430, enrolled: 44100, price: 0,   tags: ["TikTok","Reels","Video"],           description: "Crack the short-form video algorithm. Hooks, storytelling, and consistency systems.", isNew: true },
  { id: 21, title: "Brand Deals & Influencer Marketing",              instructor: "Rosine Mugenzi",         avatar: "RM", category: "Social Media Branding",  categorySlug: "social-media-branding",  level: "Advanced",     duration: "12h 00m", lessons: 46,  rating: 4.9, reviews: 1640, enrolled: 9300,  price: 59,  tags: ["Influencer","Brand Deals"],         description: "Land brand partnerships, negotiate deals, and build sustainable income as a creator." },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
export const LEVEL_BADGE: Record<string, string> = {
  Beginner:     "bg-emerald-100 text-emerald-700 border-emerald-200",
  Intermediate: "bg-blue-100 text-blue-700 border-blue-200",
  Advanced:     "bg-rose-100 text-rose-700 border-rose-200",
};