import { useEffect, useState } from "react"
import { FiAlertTriangle, FiCheck, FiRefreshCw, FiSearch, FiFileText, FiChevronDown } from "react-icons/fi"
import { Loader2, AlertTriangle, CheckCircle, Clock } from "lucide-react"
import { getAbuseReports, resolveAbuseReport, reopenAbuseReport } from "../Services/AdminService"
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface AbuseReport {
  _id: string;
  id: string;
  reportedBy: { name: string; email: string };
  targetType: string;
  targetId: string;
  reason: string;
  description: string;
  status: string;
  createdAt: string;
}

const AbuseReportsManagement = () => {
  const [reports, setReports] = useState<AbuseReport[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [actionLoading, setActionLoading] = useState<string | null>(null)
  const [filter, setFilter] = useState<"ALL" | "PENDING" | "RESOLVED">("ALL")
  const [searchTerm, setSearchTerm] = useState("")
  const [showExportMenu, setShowExportMenu] = useState(false)

  useEffect(() => {
    fetchReports()
  }, [])

  const fetchReports = async () => {
    try {
      setLoading(true)
      setError("")
      console.log('Fetching abuse reports...')
      const data = await getAbuseReports()
      console.log('Abuse reports data:', data)
      const reportsArray = Array.isArray(data) ? data : (data.reports || [])
      setReports(reportsArray)
    } catch (err: any) {
      console.error('Fetch abuse reports error:', err)
      setError(err.response?.data?.error || "Failed to load abuse reports")
    } finally {
      setLoading(false)
    }
  }

  const handleResolve = async (reportId: string) => {
    try {
      setActionLoading(reportId)
      setError("")
      console.log('Resolving report:', reportId)
      await resolveAbuseReport(reportId)
      setSuccess("Report resolved successfully")
      setTimeout(() => setSuccess(""), 3000)
      fetchReports()
    } catch (err: any) {
      console.error('Resolve error:', err)
      setError(err.response?.data?.error || "Failed to resolve report")
    } finally {
      setActionLoading(null)
    }
  }

  const handleReopen = async (reportId: string) => {
    try {
      setActionLoading(reportId)
      setError("")
      console.log('Reopening report:', reportId)
      await reopenAbuseReport(reportId)
      setSuccess("Report reopened successfully")
      setTimeout(() => setSuccess(""), 3000)
      fetchReports()
    } catch (err: any) {
      console.error('Reopen error:', err)
      setError(err.response?.data?.error || "Failed to reopen report")
    } finally {
      setActionLoading(null)
    }
  }

  const filteredReports = reports
    .filter(report => filter === "ALL" || report.status === filter)
    .filter(report => 
      report.reportedBy?.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      report.reason.toLowerCase().includes(searchTerm.toLowerCase())
    )

  const stats = {
    total: filteredReports.length,
    pending: filteredReports.filter(r => r.status === 'OPEN').length,
    resolved: filteredReports.filter(r => r.status === 'DISMISSED').length,
  }

  const exportToCSV = () => {
    const headers = ['#', 'Reporter', 'Email', 'Target Type', 'Reason', 'Status', 'Date'];
    const rows = filteredReports.map((r, idx) => [
      idx + 1,
      r.reportedBy?.name || 'Unknown',
      r.reportedBy?.email || 'N/A',
      r.targetType,
      r.reason,
      r.status === 'DISMISSED' ? 'RESOLVED' : r.status,
      r.createdAt ? new Date(r.createdAt).toLocaleDateString() : 'N/A'
    ]);
    const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `abuse_reports_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    setShowExportMenu(false);
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(44, 122, 123);
    doc.text('SupportHub', 14, 20);
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Abuse Reports Management Report', 14, 30);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const generatedBy = JSON.parse(localStorage.getItem('user') || '{}').name || 'Admin';
    const generatedAt = new Date().toLocaleString();
    doc.text(`Generated by: ${generatedBy}`, 14, 38);
    doc.text(`Generated at: ${generatedAt}`, 14, 43);
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total: ${stats.total} | Pending: ${stats.pending} | Resolved: ${stats.resolved}`, 14, 50);
    autoTable(doc, {
      startY: 55,
      head: [['#', 'Reporter', 'Target Type', 'Reason', 'Status', 'Date']],
      body: filteredReports.map((r, idx) => [
        idx + 1,
        r.reportedBy?.name || 'Unknown',
        r.targetType,
        r.reason,
        r.status === 'DISMISSED' ? 'RESOLVED' : r.status,
        r.createdAt ? new Date(r.createdAt).toLocaleDateString() : 'N/A'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [44, 122, 123] },
      styles: { fontSize: 8 },
    });
    doc.save(`abuse_reports_${new Date().toISOString().split('T')[0]}.pdf`);
    setShowExportMenu(false);
  };

  const exportToJSON = () => {
    const data = filteredReports.map((r, idx) => ({
      number: idx + 1,
      reporter: r.reportedBy?.name || 'Unknown',
      email: r.reportedBy?.email || 'N/A',
      targetType: r.targetType,
      reason: r.reason,
      description: r.description,
      status: r.status === 'DISMISSED' ? 'RESOLVED' : r.status,
      date: r.createdAt ? new Date(r.createdAt).toLocaleDateString() : 'N/A'
    }));
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `abuse_reports_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    setShowExportMenu(false);
  };

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold">Abuse Reports</h1>
          <p className="text-gray-500">Review and manage abuse reports</p>
        </div>
        <div className="relative">
          <button
            onClick={() => setShowExportMenu(!showExportMenu)}
            className="flex items-center gap-2 px-4 py-2 bg-[#2C7A7B] text-white rounded-lg hover:bg-[#235E5F] transition shadow-md"
          >
            <FiFileText size={16} />
            Export
            <FiChevronDown className={`transition-transform ${showExportMenu ? 'rotate-180' : ''}`} />
          </button>
          {showExportMenu && (
            <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-xl border border-gray-200 z-50">
              <div className="p-2">
                <button
                  onClick={exportToCSV}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 rounded transition"
                >
                  Export as CSV
                </button>
                <button
                  onClick={exportToPDF}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 rounded transition"
                >
                  Export as PDF
                </button>
                <button
                  onClick={exportToJSON}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 rounded transition"
                >
                  Export as JSON
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Total Reports</p>
              <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
            </div>
            <AlertTriangle className="w-8 h-8 text-orange-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Pending</p>
              <p className="text-2xl font-bold text-yellow-600">{stats.pending}</p>
            </div>
            <Clock className="w-8 h-8 text-yellow-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Resolved</p>
              <p className="text-2xl font-bold text-green-600">{stats.resolved}</p>
            </div>
            <CheckCircle className="w-8 h-8 text-green-500" />
          </div>
        </div>
      </div>

      <div className="bg-white rounded-xl p-4 shadow-sm mb-6 flex gap-4">
        <div className="relative flex-1">
          <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="Search by reporter or reason..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#2C7A7B] focus:border-transparent"
          />
        </div>
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value as "ALL" | "PENDING" | "RESOLVED")}
          className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#2C7A7B] focus:border-transparent"
        >
          <option value="ALL">All Status</option>
          <option value="PENDING">Pending</option>
          <option value="RESOLVED">Resolved</option>
        </select>
      </div>

      {success && (
        <div className="mb-6 flex items-start gap-2 p-3 bg-green-50 border border-green-200 rounded-lg">
          <FiCheck className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-green-700">{success}</p>
        </div>
      )}

      {error && (
        <div className="mb-6 flex items-start gap-2 p-3 bg-red-50 border border-red-200 rounded-lg">
          <FiAlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-red-700">{error}</p>
        </div>
      )}

      {loading ? (
        <div className="bg-white rounded-xl p-8 flex items-center justify-center">
          <Loader2 className="w-6 h-6 animate-spin text-[#2C7A7B] mr-2" />
          <span className="text-gray-600">Loading reports...</span>
        </div>
      ) : filteredReports.length === 0 ? (
        <div className="bg-white rounded-xl p-8 text-center">
          <FiAlertTriangle className="w-12 h-12 mx-auto mb-3 text-gray-300" />
          <p className="text-gray-600 font-medium mb-2">No abuse reports</p>
          <p className="text-sm text-gray-400">Reports will appear here when users submit them</p>
        </div>
      ) : (
        <div className="bg-white rounded-xl shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">#</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Reporter</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Target Type</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Reason</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Description</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filteredReports.map((report, index) => (
                  <tr key={report._id || report.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 text-sm font-medium text-gray-900">{index + 1}</td>
                    <td className="px-6 py-4">
                      <div>
                        <p className="font-medium text-gray-900">{report.reportedBy?.name || "Unknown"}</p>
                        <p className="text-sm text-gray-500">{report.reportedBy?.email || "N/A"}</p>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className="px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700">
                        {report.targetType}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">{report.reason || "N/A"}</td>
                    <td className="px-6 py-4 text-sm text-gray-600 max-w-xs truncate">{report.description || ""}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        report.status === "DISMISSED" ? "bg-green-100 text-green-700" : "bg-yellow-100 text-yellow-700"
                      }`}>
                        {report.status === "DISMISSED" ? "RESOLVED" : report.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">
                      {report.createdAt ? new Date(report.createdAt).toLocaleDateString() : "N/A"}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex gap-2">
                        {report.status === "OPEN" ? (
                          <button 
                            onClick={() => handleResolve(report.id || report._id)}
                            disabled={actionLoading === (report.id || report._id)}
                            className="p-2 rounded-lg bg-green-100 text-green-700 hover:bg-green-200 disabled:opacity-50 transition"
                            title="Resolve report"
                          >
                            {actionLoading === (report.id || report._id) ? <Loader2 className="w-4 h-4 animate-spin" /> : <FiCheck className="w-4 h-4" />}
                          </button>
                        ) : (
                          <button
                            onClick={() => handleReopen(report.id || report._id)}
                            disabled={actionLoading === (report.id || report._id)}
                            className="p-2 rounded-lg bg-blue-100 text-blue-700 hover:bg-blue-200 disabled:opacity-50 transition"
                            title="Reopen report"
                          >
                            {actionLoading === (report.id || report._id) ? <Loader2 className="w-4 h-4 animate-spin" /> : <FiRefreshCw className="w-4 h-4" />}
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}

export default AbuseReportsManagement
