import { useEffect, useState } from "react"
import { FiEdit2, FiTrash2, FiPlus, FiX, FiFileText } from "react-icons/fi"
import { Loader2, FolderOpen, FolderCheck, Folder } from "lucide-react"
import Categoryservice, { type Category } from "../Services/Categoryservice"
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const CategoriesManagement = () => {
  const [categories, setCategories] = useState<Category[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [actionLoading, setActionLoading] = useState<string | null>(null)

  const [showModal, setShowModal] = useState(false)
  const [editMode, setEditMode] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [newCategory, setNewCategory] = useState({ name: "", description: "" })
  const [submitting, setSubmitting] = useState(false)
  const [success, setSuccess] = useState("")

  // Fetch categories on component mount
  useEffect(() => {
    fetchCategories()
  }, [])

  const fetchCategories = async () => {
    try {
      setLoading(true)
      setError("")
      const categoriesData = await Categoryservice.getCategories()
      console.log('Categories data:', categoriesData)
      setCategories(categoriesData)
    } catch {
      setError("Failed to load categories")
    } finally {
      setLoading(false)
    }
  }

  const handleAddCategory = async () => {
    if (!newCategory.name || !newCategory.description) {
      setError("Category name and description are required")
      return
    }

    try {
      setSubmitting(true)
      setError("")
      if (editMode && editingId) {
        await Categoryservice.updateCategory(editingId, newCategory)
        setSuccess("Category updated successfully")
      } else {
        await Categoryservice.createCategory(newCategory)
        setSuccess("Category created successfully")
      }
      setTimeout(() => setSuccess(""), 3000)
      fetchCategories()
      setNewCategory({ name: "", description: "" })
      setShowModal(false)
      setEditMode(false)
      setEditingId(null)
    } catch (err: unknown) {
      if (err instanceof Error && (err.message.includes('409') || err.message.toLowerCase().includes('conflict') || err.message.toLowerCase().includes('already exists'))) {
        setError(`Category "${newCategory.name}" already exists. Please use a different name.`)
      } else {
        setError(`Failed to ${editMode ? 'update' : 'create'} category`)
      }
    } finally {
      setSubmitting(false)
    }
  }

  const handleEdit = (category: Category) => {
    setEditMode(true)
    setEditingId(category.id)
    setNewCategory({ name: category.name, description: category.description || "" })
    setShowModal(true)
  }

  const handleCloseModal = () => {
    setShowModal(false)
    setEditMode(false)
    setEditingId(null)
    setNewCategory({ name: "", description: "" })
    setError("")
  }

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(44, 122, 123);
    doc.text('SupportHub', 14, 20);
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Categories Management Report', 14, 30);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const generatedBy = JSON.parse(localStorage.getItem('user') || '{}').name || 'Admin';
    const generatedAt = new Date().toLocaleString();
    doc.text(`Generated by: ${generatedBy}`, 14, 38);
    doc.text(`Generated at: ${generatedAt}`, 14, 43);
    const activeCount = categories.filter(c => c.isActive).length;
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total: ${categories.length} | Active: ${activeCount} | Inactive: ${categories.length - activeCount}`, 14, 50);
    autoTable(doc, {
      startY: 55,
      head: [['#', 'Name', 'Description', 'Status', 'Created']],
      body: categories.map((c, idx) => [
        idx + 1,
        c.name,
        c.description || 'N/A',
        c.isActive ? 'Active' : 'Inactive',
        c.createdAt ? new Date(c.createdAt).toLocaleDateString() : 'N/A'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [44, 122, 123] },
      styles: { fontSize: 9 },
    });
    doc.save(`categories_report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handleDelete = async (categoryId: string) => {
    if (window.confirm("Are you sure you want to delete this category?")) {
      try {
        setActionLoading(categoryId)
        setError("")
        await Categoryservice.deleteCategory(categoryId)
        setSuccess("Category deleted successfully")
        setTimeout(() => setSuccess(""), 3000)
        fetchCategories()
      } catch {
        setError("Failed to delete category")
      } finally {
        setActionLoading(null)
      }
    }
  }

  return (
    <div>
      <div className='space-y-2 sm:flex justify-between items-center mb-6' >
        <div>
          <h1 style={{ fontSize: '28px', fontWeight: 'bold', margin: 0 }}>Manage Categories</h1>
          <p style={{ color: '#6b7280', margin: '8px 0 0 0' }}>Create and manage content categories</p>
        </div>

        
        <button
          onClick={() => setShowModal(true)}
          disabled={submitting}
          style={{ backgroundColor: '#2C7A7B', color: 'white', padding: '8px 16px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '8px', border: 'none', cursor: 'pointer', opacity: submitting ? 0.6 : 1 }}
        >
          <FiPlus size={18} /> New Category
        </button>
      </div>
<div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '16px', marginBottom: '24px' }}>
        <div style={{ backgroundColor: 'white', padding: '16px', borderRadius: '12px', border: '1px solid #e5e7eb' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <p style={{ fontSize: '14px', color: '#6b7280', margin: 0 }}>Total Categories</p>
              <p style={{ fontSize: '28px', fontWeight: 'bold', color: '#111827', margin: '4px 0 0 0' }}>{categories.length}</p>
            </div>
            <Folder style={{ width: '32px', height: '32px', color: '#3b82f6' }} />
          </div>
        </div>
        <div style={{ backgroundColor: 'white', padding: '16px', borderRadius: '12px', border: '1px solid #e5e7eb' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <p style={{ fontSize: '14px', color: '#6b7280', margin: 0 }}>Active Categories</p>
              <p style={{ fontSize: '28px', fontWeight: 'bold', color: '#16a34a', margin: '4px 0 0 0' }}>{categories.filter(c => c.isActive).length}</p>
            </div>
            <FolderCheck style={{ width: '32px', height: '32px', color: '#16a34a' }} />
          </div>
        </div>
        <div style={{ backgroundColor: 'white', padding: '16px', borderRadius: '12px', border: '1px solid #e5e7eb' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <p style={{ fontSize: '14px', color: '#6b7280', margin: 0 }}>Inactive Categories</p>
              <p style={{ fontSize: '28px', fontWeight: 'bold', color: '#dc2626', margin: '4px 0 0 0' }}>{categories.filter(c => !c.isActive).length}</p>
            </div>
            <FolderOpen style={{ width: '32px', height: '32px', color: '#dc2626' }} />
          </div>
        </div>
      </div>


      <div style={{ backgroundColor: 'white', padding: '16px', borderRadius: '12px', marginBottom: '24px', border: '1px solid #e5e7eb' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div style={{ flex: 1 }}>
            <input
              type="text"
              placeholder="Search categories..."
              style={{ width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '8px', outline: 'none' }}
            />
          </div>
          <button
            onClick={exportToPDF}
            style={{ backgroundColor: '#2C7A7B', color: 'white', padding: '8px 16px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '8px', border: 'none', cursor: 'pointer', whiteSpace: 'nowrap' }}
          >
            <FiFileText size={16} /> Export PDF
          </button>
        </div>
      </div>

      

      {success && (
        <div style={{ backgroundColor: '#d1fae5', padding: '12px 16px', borderRadius: '8px', color: '#065f46', marginBottom: '16px', fontSize: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          ✓ {success}
        </div>
      )}

      {error && (
        <div style={{ backgroundColor: '#fee2e2', padding: '12px 16px', borderRadius: '8px', color: '#991b1b', marginBottom: '16px', fontSize: '14px' }}>
          ⚠️ {error}
        </div>
      )}

      {showModal && (
        <div style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 }}>
          <div style={{ backgroundColor: 'white', borderRadius: '8px', padding: '24px', maxWidth: '448px', width: '100%', margin: '0 16px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h2 style={{ fontSize: '20px', fontWeight: 'bold', margin: 0 }}>{editMode ? 'Edit Category' : 'Create New Category'}</h2>
              <button onClick={handleCloseModal} style={{ padding: '4px', border: 'none', background: 'none', cursor: 'pointer' }}>
                <FiX size={20} />
              </button>
            </div>
            <input
              type="text"
              placeholder="Category name"
              value={newCategory.name}
              onChange={(e) => setNewCategory({ ...newCategory, name: e.target.value })}
              disabled={submitting}
              style={{ width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '8px', marginBottom: '12px', outline: 'none' }}
            />
            <textarea
              placeholder="Category description"
              value={newCategory.description}
              onChange={(e) => setNewCategory({ ...newCategory, description: e.target.value })}
              disabled={submitting}
              style={{ width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '8px', marginBottom: '16px', outline: 'none', resize: 'none' }}
              rows={3}
            />
            <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
              <button
                onClick={handleCloseModal}
                disabled={submitting}
                style={{ padding: '8px 16px', border: '1px solid #d1d5db', borderRadius: '8px', backgroundColor: 'white', cursor: 'pointer', opacity: submitting ? 0.6 : 1 }}
              >
                Cancel
              </button>
              <button
                onClick={handleAddCategory}
                disabled={submitting}
                style={{ padding: '8px 16px', backgroundColor: '#2C7A7B', color: 'white', borderRadius: '8px', border: 'none', cursor: 'pointer', opacity: submitting ? 0.6 : 1 }}
              >
                {submitting ? (editMode ? "Updating..." : "Creating...") : (editMode ? "Update" : "Create")}
              </button>
            </div>
          </div>
        </div>
      )}

      {loading ? (
        <div style={{ textAlign: 'center', padding: '40px 20px', backgroundColor: 'white', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>
          <Loader2 style={{ width: '20px', height: '20px', animation: 'spin 1s linear infinite' }} />
          <p style={{ color: '#6b7280', margin: 0 }}>Loading categories...</p>
        </div>
      ) : categories.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '40px 20px', backgroundColor: 'white', borderRadius: '8px' }}>
          <p style={{ color: '#6b7280' }}>No categories found. Create one to get started!</p>
        </div>
      ) : (
        <div style={{ backgroundColor: 'white', borderRadius: '8px', overflow: 'hidden', border: '1px solid #e5e7eb' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead style={{ backgroundColor: '#f9fafb', borderBottom: '1px solid #e5e7eb' }}>
              <tr>
                <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' }}>#</th>
                <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' }}>Name</th>
                <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' }}>Description</th>
                <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' }}>Status</th>
                <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' }}>Created</th>
                <th style={{ padding: '12px 16px', textAlign: 'center', fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {categories.map((category, index) => (
                <tr key={category.id} style={{ borderBottom: '1px solid #e5e7eb' }}>
                  <td style={{ padding: '12px 16px', fontSize: '14px', color: '#374151' }}>{index + 1}</td>
                  <td style={{ padding: '12px 16px', fontSize: '14px', fontWeight: '500', color: '#111827' }}>{category.name || "N/A"}</td>
                  <td style={{ padding: '12px 16px', fontSize: '14px', color: '#6b7280', maxWidth: '300px' }}>{category.description || "No description"}</td>
                  <td style={{ padding: '12px 16px' }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '4px 8px', borderRadius: '12px', fontSize: '12px', fontWeight: '500', backgroundColor: category.isActive ? '#d1fae5' : '#fee2e2', color: category.isActive ? '#065f46' : '#991b1b' }}>
                      {category.isActive ? <FolderCheck size={14} /> : <FolderOpen size={14} />}
                      {category.isActive ? "Active" : "Inactive"}
                    </span>
                  </td>
                  <td style={{ padding: '12px 16px', fontSize: '14px', color: '#6b7280' }}>
                    {category.createdAt ? new Date(category.createdAt).toLocaleDateString() : "N/A"}
                  </td>
                  <td style={{ padding: '12px 16px' }}>
                    <div style={{ display: 'flex', gap: '8px', justifyContent: 'center' }}>
                      <button
                        onClick={() => handleEdit(category)}
                        disabled={actionLoading === category.id}
                        style={{ padding: '6px 12px', backgroundColor: '#fed7aa', color: '#92400e', borderRadius: '6px', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '13px', opacity: actionLoading === category.id ? 0.6 : 1 }}
                      >
                        <FiEdit2 size={14} /> Edit
                      </button>
                      <button
                        onClick={() => handleDelete(category.id)}
                        disabled={actionLoading === category.id}
                        style={{ padding: '6px 12px', backgroundColor: '#fee2e2', color: '#991b1b', borderRadius: '6px', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '13px', opacity: actionLoading === category.id ? 0.6 : 1 }}
                      >
                        <FiTrash2 size={14} /> Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}

export default CategoriesManagement
