import { useEffect, useState } from "react"
import { FiXCircle, FiCheck, FiClock, FiAlertCircle, FiSearch, FiFileText, FiChevronDown } from "react-icons/fi"
import { Loader2, FileText, CheckCircle, XCircle, Clock } from "lucide-react"
import { getRequests, approveRequest, rejectRequest } from "../Services/AdminService"
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface Request {
  _id: string;
  id: string;
  title: string;
  type: "REQUEST" | "OFFER";
  author: { name: string };
  category: { name: string };
  description: string;
  status: string;
  createdAt: string;
}

const RequestsManagement = () => {
  const [requests, setRequests] = useState<Request[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [success, setSuccess] = useState("")
  const [actionLoading, setActionLoading] = useState<string | null>(null)
  const [filter, setFilter] = useState<"ALL" | "REQUEST" | "OFFER">("ALL")
  const [statusFilter, setStatusFilter] = useState<"ALL" | "PENDING" | "APPROVED" | "REJECTED">("ALL")
  const [searchTerm, setSearchTerm] = useState("")
  const [showExportMenu, setShowExportMenu] = useState(false)

  useEffect(() => {
    fetchRequests()
  }, [])

  const fetchRequests = async () => {
    try {
      setLoading(true)
      setError("")
      console.log('Fetching requests...')
      const data = await getRequests()
      console.log('Requests data:', data)
      const requestsArray = Array.isArray(data) ? data : (data.requests || [])
      setRequests(requestsArray)
    } catch (err: any) {
      console.error('Fetch requests error:', err)
      setError(err.response?.data?.error || "Failed to load requests")
    } finally {
      setLoading(false)
    }
  }

  const handleApproveRequest = async (id: string) => {
    try {
      setActionLoading(id)
      setError("")
      console.log('Approving request:', id)
      await approveRequest(id)
      setSuccess("Request approved successfully")
      setTimeout(() => setSuccess(""), 3000)
      fetchRequests()
    } catch (err: any) {
      console.error('Approve request error:', err)
      setError(err.response?.data?.error || "Failed to approve request")
    } finally {
      setActionLoading(null)
    }
  }

  const handleRejectRequest = async (id: string) => {
    if (!window.confirm("Are you sure you want to reject this request?")) return
    try {
      setActionLoading(id)
      setError("")
      console.log('Rejecting request:', id)
      await rejectRequest(id)
      setSuccess("Request rejected successfully")
      setTimeout(() => setSuccess(""), 3000)
      fetchRequests()
    } catch (err: any) {
      console.error('Reject request error:', err)
      setError(err.response?.data?.error || "Failed to reject request")
    } finally {
      setActionLoading(null)
    }
  }

  const filteredRequests = requests
    .filter(req => filter === "ALL" || req.type === filter)
    .filter(req => statusFilter === "ALL" || req.status === statusFilter)
    .filter(req => 
      req.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      req.author?.name.toLowerCase().includes(searchTerm.toLowerCase())
    )

  const stats = {
    total: filteredRequests.length,
    pending: filteredRequests.filter(r => r.status === 'PENDING').length,
    approved: filteredRequests.filter(r => r.status === 'APPROVED').length,
    rejected: filteredRequests.filter(r => r.status === 'REJECTED').length,
  }

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(44, 122, 123);
    doc.text('SupportHub', 14, 20);
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Requests Management Report', 14, 30);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const generatedBy = JSON.parse(localStorage.getItem('user') || '{}').name || 'Admin';
    const generatedAt = new Date().toLocaleString();
    doc.text(`Generated by: ${generatedBy}`, 14, 38);
    doc.text(`Generated at: ${generatedAt}`, 14, 43);
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total: ${stats.total} | Pending: ${stats.pending} | Approved: ${stats.approved} | Rejected: ${stats.rejected}`, 14, 50);
    autoTable(doc, {
      startY: 55,
      head: [['#', 'Title', 'Type', 'Author', 'Category', 'Status', 'Created']],
      body: filteredRequests.map((r, idx) => [
        idx + 1,
        r.title || 'N/A',
        r.type,
        r.author?.name || 'Unknown',
        r.category?.name || 'N/A',
        r.status,
        r.createdAt ? new Date(r.createdAt).toLocaleDateString() : 'N/A'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [44, 122, 123] },
      styles: { fontSize: 8 },
    });
    doc.save(`requests_report_${new Date().toISOString().split('T')[0]}.pdf`);
    setShowExportMenu(false);
  };

  const exportToCSV = () => {
    const headers = ['#', 'Title', 'Type', 'Author', 'Category', 'Status', 'Created'];
    const rows = filteredRequests.map((r, idx) => [
      idx + 1,
      r.title || 'N/A',
      r.type,
      r.author?.name || 'Unknown',
      r.category?.name || 'N/A',
      r.status,
      r.createdAt ? new Date(r.createdAt).toLocaleDateString() : 'N/A'
    ]);
    const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `requests_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    setShowExportMenu(false);
  };

  const exportToJSON = () => {
    const data = filteredRequests.map((r, idx) => ({
      number: idx + 1,
      title: r.title || 'N/A',
      type: r.type,
      author: r.author?.name || 'Unknown',
      category: r.category?.name || 'N/A',
      description: r.description,
      status: r.status,
      created: r.createdAt ? new Date(r.createdAt).toLocaleDateString() : 'N/A'
    }));
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `requests_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    setShowExportMenu(false);
  };

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold">Requests Management</h1>
          <p className="text-gray-500">Review and manage all service requests</p>
        </div>
       
      </div>

      <div className=" grid md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Total Requests</p>
              <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
            </div>
            <FileText className="w-8 h-8 text-blue-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Pending</p>
              <p className="text-2xl font-bold text-yellow-600">{stats.pending}</p>
            </div>
            <Clock className="w-8 h-8 text-yellow-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Approved</p>
              <p className="text-2xl font-bold text-green-600">{stats.approved}</p>
            </div>
            <CheckCircle className="w-8 h-8 text-green-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-xl shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Rejected</p>
              <p className="text-2xl font-bold text-red-600">{stats.rejected}</p>
            </div>
            <XCircle className="w-8 h-8 text-red-500" />
          </div>
        </div>
      </div>

      <div className="bg-white rounded-xl p-4 shadow-sm mb-6 space-y-2 lg:flex gap-4">
        <div className="relative flex-1">
          <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="Search by title or author..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className=" w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#2C7A7B] focus:border-transparent"
          />
        </div>
        <div >
           <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value as "ALL" | "PENDING" | "APPROVED" | "REJECTED")}
          className="px-4 w-full py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#2C7A7B] focus:border-transparent"
        >
          <option value="ALL">All Status</option>
          <option value="PENDING">Pending</option>
          <option value="APPROVED">Approved</option>
          <option value="REJECTED">Rejected</option>
        </select>
        </div>

        <div>
           <select
          value={filter}
          onChange={(e) => setFilter(e.target.value as "ALL" | "REQUEST" | "OFFER")}
          className="px-4 py-2 border w-full border-gray-300 rounded-lg focus:ring-2 focus:ring-[#2C7A7B] focus:border-transparent"
        >
          <option value="ALL">All Types</option>
          <option value="REQUEST">Requests Only</option>
          <option value="OFFER">Offers Only</option>
        </select>
        </div>
       
       
         <div className="relative">
          <button
            onClick={() => setShowExportMenu(!showExportMenu)}
            className="flex w-full items-center gap-2 px-4 py-2 bg-[#2C7A7B] text-white rounded-lg hover:bg-[#235E5F] transition shadow-md"
          >
            <FiFileText size={16} />
            Export
            <FiChevronDown className={`transition-transform ${showExportMenu ? 'rotate-180' : ''}`} />
          </button>
          {showExportMenu && (
            <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-xl border border-gray-200 z-50">
              <div className="p-2">
                <button
                  onClick={exportToCSV}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 rounded transition"
                >
                  Export as CSV
                </button>
                <button
                  onClick={exportToPDF}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 rounded transition"
                >
                  Export as PDF
                </button>
                <button
                  onClick={exportToJSON}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-100 rounded transition"
                >
                  Export as JSON
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {success && (
        <div className="mb-6 flex items-start gap-2 p-3 bg-green-50 border border-green-200 rounded-lg">
          <FiCheck className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-green-700">{success}</p>
        </div>
      )}

      {error && (
        <div className="mb-6 flex items-start gap-2 p-3 bg-red-50 border border-red-200 rounded-lg">
          <FiAlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-red-700">{error}</p>
        </div>
      )}

      {loading ? (
        <div className="bg-white rounded-xl p-8 flex items-center justify-center">
          <Loader2 className="w-6 h-6 animate-spin text-[#2C7A7B] mr-2" />
          <span className="text-gray-600">Loading requests...</span>
        </div>
      ) : filteredRequests.length === 0 ? (
        <div className="bg-white rounded-xl p-8 text-center">
          <FiClock className="w-12 h-12 mx-auto mb-3 text-gray-300" />
          <p className="text-gray-600 font-medium mb-2">No requests found</p>
          <p className="text-sm text-gray-400">Try adjusting your filters</p>
        </div>
      ) : (
        <div className="bg-white rounded-xl shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">#</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Title</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Type</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Author</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Category</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Description</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Created</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filteredRequests.map((request, index) => (
                  <tr key={request._id || request.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 text-sm font-medium text-gray-900">{index + 1}</td>
                    <td className="px-6 py-4 font-medium text-gray-900">{request.title || "N/A"}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        request.type === "OFFER" ? "bg-orange-100 text-orange-700" : "bg-blue-100 text-blue-700"
                      }`}>
                        {request.type}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">{request.author?.name || "Unknown"}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{request.category?.name || "N/A"}</td>
                    <td className="px-6 py-4 text-sm text-gray-600 max-w-xs truncate">{request.description || ""}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        request.status === "APPROVED" ? "bg-green-100 text-green-700" : 
                        request.status === "REJECTED" ? "bg-red-100 text-red-700" : 
                        "bg-yellow-100 text-yellow-700"
                      }`}>
                        {request.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">
                      {request.createdAt ? new Date(request.createdAt).toLocaleDateString() : "N/A"}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex gap-2">
                        {request.status === "PENDING" && (
                          <>
                            <button 
                              onClick={() => handleApproveRequest(request.id || request._id)}
                              disabled={actionLoading === (request.id || request._id)}
                              className="p-2 rounded-lg bg-green-100 text-green-700 hover:bg-green-200 disabled:opacity-50 transition"
                              title="Approve request"
                            >
                              {actionLoading === (request.id || request._id) ? <Loader2 className="w-4 h-4 animate-spin" /> : <FiCheck className="w-4 h-4" />}
                            </button>
                            <button
                              onClick={() => handleRejectRequest(request.id || request._id)}
                              disabled={actionLoading === (request.id || request._id)}
                              className="p-2 rounded-lg bg-red-100 text-red-700 hover:bg-red-200 disabled:opacity-50 transition"
                              title="Reject request"
                            >
                              <FiXCircle className="w-4 h-4" />
                            </button>
                          </>
                        )}
                        {request.status !== "PENDING" && (
                          <span className="text-sm text-gray-500 italic">No actions available</span>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}

export default RequestsManagement