export const COHORTS = [
  {
    id: "a1b2c3d4-0001",
    name: "Full-Stack Web Development",
    subtitle: "From zero to full-stack developer in 12 weeks",
    start_date: "2026-04-14",
    end_date: "2026-07-07",
    enrollment_open_date: "2026-03-01",
    enrollment_close_date: "2026-04-10",
    extension_date: "2026-07-21",
    course_type: "development",
    is_active: true,
    created_at: "2026-01-15",
    featured: true,
    // UI extras
    instructor: { name: "Freddy Bijanja", role: "Lead Instructor", initials: "FB", gradient: "from-blue-500 to-cyan-400" },
    seats: 24, seatsLeft: 6,
    rating: 4.9, reviews: 148,
    topics: ["HTML & CSS", "JavaScript", "React", "Node.js", "Databases"],
    sessions: "3x / week",
    level: "Beginner",
    gradient: "from-blue-600 to-cyan-500",
  },
  {
    id: "a1b2c3d4-0002",
    name: "UI/UX Design Mastery",
    subtitle: "Design beautiful products people love to use",
    start_date: "2026-04-21",
    end_date: "2026-06-16",
    enrollment_open_date: "2026-03-10",
    enrollment_close_date: "2026-04-18",
    extension_date: "2026-06-23",
    course_type: "design",
    is_active: true,
    created_at: "2026-01-20",
    featured: false,
    instructor: { name: "IRADUKUNDA Boris", role: "Design Lead", initials: "IB", gradient: "from-violet-500 to-pink-400" },
    seats: 20, seatsLeft: 12,
    rating: 4.8, reviews: 93,
    topics: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
    sessions: "2x / week",
    level: "All Levels",
    gradient: "from-violet-500 to-pink-500",
  },
  {
    id: "a1b2c3d4-0003",
    name: "Data Science & Analytics",
    subtitle: "Turn raw data into actionable insights",
    start_date: "2026-02-03",
    end_date: "2026-04-14",
    enrollment_open_date: "2026-01-05",
    enrollment_close_date: "2026-01-30",
    extension_date: "2026-04-28",
    course_type: "data",
    is_active: true,
    created_at: "2025-12-01",
    featured: false,
    instructor: { name: "Olivier Nduwayesu", role: "Data Engineer", initials: "ON", gradient: "from-emerald-500 to-teal-400" },
    seats: 18, seatsLeft: 0,
    rating: 4.9, reviews: 76,
    topics: ["Python", "Pandas", "SQL", "Visualization", "ML Basics"],
    sessions: "2x / week",
    level: "Intermediate",
    gradient: "from-emerald-500 to-teal-400",
  },
  {
    id: "a1b2c3d4-0004",
    name: "Digital Marketing Strategy",
    subtitle: "Build and scale brands in the digital age",
    start_date: "2026-05-05",
    end_date: "2026-06-16",
    enrollment_open_date: "2026-04-01",
    enrollment_close_date: "2026-05-01",
    extension_date: "2026-06-23",
    course_type: "business",
    is_active: false,
    created_at: "2026-02-10",
    featured: false,
    instructor: { name: "Sarah Amara", role: "Marketing Expert", initials: "SA", gradient: "from-amber-400 to-orange-400" },
    seats: 30, seatsLeft: 30,
    rating: null, reviews: 0,
    topics: ["SEO", "Content Strategy", "Paid Ads", "Analytics", "Social Media"],
    sessions: "2x / week",
    level: "All Levels",
    gradient: "from-amber-400 to-orange-400",
  },
  {
    id: "a1b2c3d4-0005",
    name: "Mobile App Development",
    subtitle: "Ship iOS and Android apps with React Native",
    start_date: "2026-04-28",
    end_date: "2026-07-07",
    enrollment_open_date: "2026-03-15",
    enrollment_close_date: "2026-04-24",
    extension_date: "2026-07-14",
    course_type: "development",
    is_active: true,
    created_at: "2026-01-28",
    featured: false,
    instructor: { name: "Freddy Bijanja", role: "Lead Instructor", initials: "FB", gradient: "from-blue-500 to-cyan-400" },
    seats: 15, seatsLeft: 3,
    rating: 4.7, reviews: 54,
    topics: ["React Native", "Expo", "Navigation", "APIs", "App Store"],
    sessions: "2x / week",
    level: "Intermediate",
    gradient: "from-rose-500 to-pink-500",
  },
  {
    id: "a1b2c3d4-0006",
    name: "Public Speaking & Communication",
    subtitle: "Communicate with confidence and clarity",
    start_date: "2026-01-06",
    end_date: "2026-02-03",
    enrollment_open_date: "2025-12-01",
    enrollment_close_date: "2026-01-03",
    extension_date: "2026-02-10",
    course_type: "personal",
    is_active: false,
    created_at: "2025-11-15",
    featured: false,
    instructor: { name: "Amara Diallo", role: "Coach", initials: "AD", gradient: "from-sky-400 to-blue-400" },
    seats: 25, seatsLeft: 0,
    rating: 5.0, reviews: 41,
    topics: ["Storytelling", "Presentations", "Body Language", "Persuasion"],
    sessions: "2x / week",
    level: "All Levels",
    gradient: "from-sky-400 to-blue-500",
  },
];

export const INSTRUCTORS = {
  "ins-001": { name: "Freddy Bijanja",    role: "Lead Instructor",  initials: "FB", gradient: "from-blue-500 to-cyan-400" },
  "ins-002": { name: "IRADUKUNDA Boris",  role: "Design Lead",       initials: "IB", gradient: "from-violet-500 to-pink-400" },
  "ins-003": { name: "Olivier Nduwayesu", role: "Data Engineer",     initials: "ON", gradient: "from-emerald-500 to-teal-400" },
  "ins-004": { name: "Sarah Amara",       role: "Marketing Expert",  initials: "SA", gradient: "from-amber-400 to-orange-400" },
  "ins-005": { name: "Amara Diallo",      role: "Coach",             initials: "AD", gradient: "from-sky-400 to-blue-400" },
};

export const COHORT = {
  "coh-001": { name: "Full-Stack Cohort · Apr 2026",     gradient: "from-blue-600 to-cyan-500" },
  "coh-002": { name: "UI/UX Design Cohort · Apr 2026",   gradient: "from-violet-500 to-pink-500" },
  "coh-003": { name: "Data Science Cohort · Feb 2026",   gradient: "from-emerald-500 to-teal-400" },
  "coh-004": { name: "Marketing Cohort · May 2026",      gradient: "from-amber-400 to-orange-400" },
  "coh-005": { name: "Mobile Dev Cohort · Apr 2026",     gradient: "from-rose-500 to-pink-500" },
};

export const COURSES = [
  {
    id: "crs-0001-uuid",
    title: "Introduction to HTML & CSS",
    description: "Build solid foundations in web markup and styling. You will learn semantic HTML5, Flexbox, Grid, and responsive design patterns used in real production projects.",
    instructor_id: "ins-001",
    cohort_id: "coh-001",
    course_type: "development",
    is_published: true,
    created_at: "2026-01-10",
    // UI extras
    duration: "2 weeks", lessons: 14, level: "Beginner",
    rating: 4.9, reviews: 112, enrolled: 240,
    topics: ["HTML5", "CSS3", "Flexbox", "Grid", "Responsive"],
    gradient: "from-blue-600 to-cyan-500",
    featured: true,
  },
  {
    id: "crs-0002-uuid",
    title: "JavaScript Fundamentals",
    description: "Master the language of the web. From variables and functions to DOM manipulation and async programming — this course covers everything you need to write real JavaScript.",
    instructor_id: "ins-001",
    cohort_id: "coh-001",
    course_type: "development",
    is_published: true,
    created_at: "2026-01-12",
    duration: "3 weeks", lessons: 22, level: "Beginner",
    rating: 4.8, reviews: 98, enrolled: 210,
    topics: ["Variables", "Functions", "DOM", "Async/Await", "ES6+"],
    gradient: "from-blue-500 to-indigo-500",
    featured: false,
  },
  {
    id: "crs-0003-uuid",
    title: "React — Build Modern UIs",
    description: "Dive deep into the most popular front-end library. Components, hooks, state management, routing, and connecting to APIs. Build three complete projects from scratch.",
    instructor_id: "ins-001",
    cohort_id: "coh-001",
    course_type: "development",
    is_published: true,
    created_at: "2026-01-20",
    duration: "4 weeks", lessons: 30, level: "Intermediate",
    rating: 4.9, reviews: 87, enrolled: 195,
    topics: ["Components", "Hooks", "Redux", "React Router", "APIs"],
    gradient: "from-cyan-500 to-blue-600",
    featured: false,
  },
  {
    id: "crs-0004-uuid",
    title: "Figma for Product Designers",
    description: "Go from sketch to polished prototype. Learn auto-layout, components, variants, design tokens, and how to hand off designs to developers like a senior designer.",
    instructor_id: "ins-002",
    cohort_id: "coh-002",
    course_type: "design",
    is_published: true,
    created_at: "2026-01-15",
    duration: "2 weeks", lessons: 16, level: "All Levels",
    rating: 4.8, reviews: 74, enrolled: 168,
    topics: ["Auto-layout", "Components", "Variants", "Tokens", "Handoff"],
    gradient: "from-violet-500 to-pink-500",
    featured: false,
  },
  {
    id: "crs-0005-uuid",
    title: "User Research & UX Strategy",
    description: "Great products start with deep user understanding. Learn interviews, surveys, usability testing, and how to synthesize insights into product decisions that stick.",
    instructor_id: "ins-002",
    cohort_id: "coh-002",
    course_type: "design",
    is_published: false,
    created_at: "2026-01-18",
    duration: "2 weeks", lessons: 12, level: "Intermediate",
    rating: null, reviews: 0, enrolled: 0,
    topics: ["Interviews", "Surveys", "Usability Testing", "Personas", "Journey Maps"],
    gradient: "from-fuchsia-500 to-violet-500",
    featured: false,
  },
  {
    id: "crs-0006-uuid",
    title: "Python for Data Analysis",
    description: "Hands-on data work with Python. You will manipulate large datasets with Pandas, visualize patterns with Matplotlib and Seaborn, and query databases using SQL.",
    instructor_id: "ins-003",
    cohort_id: "coh-003",
    course_type: "data",
    is_published: true,
    created_at: "2025-12-20",
    duration: "3 weeks", lessons: 20, level: "Intermediate",
    rating: 4.9, reviews: 63, enrolled: 140,
    topics: ["Python", "Pandas", "Matplotlib", "Seaborn", "SQL"],
    gradient: "from-emerald-500 to-teal-400",
    featured: false,
  },
  {
    id: "crs-0007-uuid",
    title: "Machine Learning Basics",
    description: "Demystify machine learning. Understand supervised and unsupervised learning, train your first models with scikit-learn, and evaluate them with real-world datasets.",
    instructor_id: "ins-003",
    cohort_id: "coh-003",
    course_type: "data",
    is_published: false,
    created_at: "2026-01-05",
    duration: "3 weeks", lessons: 18, level: "Advanced",
    rating: null, reviews: 0, enrolled: 0,
    topics: ["scikit-learn", "Supervised Learning", "Clustering", "Model Evaluation"],
    gradient: "from-teal-500 to-cyan-500",
    featured: false,
  },
  {
    id: "crs-0008-uuid",
    title: "SEO & Content Marketing",
    description: "Learn how to get your content found and loved. Keyword research, on-page SEO, content calendars, and measuring performance — the full content marketing playbook.",
    instructor_id: "ins-004",
    cohort_id: "coh-004",
    course_type: "business",
    is_published: true,
    created_at: "2026-02-01",
    duration: "2 weeks", lessons: 14, level: "All Levels",
    rating: 4.7, reviews: 38, enrolled: 90,
    topics: ["Keyword Research", "On-Page SEO", "Backlinks", "Analytics", "Content Strategy"],
    gradient: "from-amber-400 to-orange-400",
    featured: false,
  },
  {
    id: "crs-0009-uuid",
    title: "React Native — Mobile Apps",
    description: "Build polished iOS and Android apps with a single codebase. Navigation, native APIs, push notifications, and publishing to the App Store and Google Play.",
    instructor_id: "ins-001",
    cohort_id: "coh-005",
    course_type: "development",
    is_published: true,
    created_at: "2026-02-05",
    duration: "4 weeks", lessons: 28, level: "Intermediate",
    rating: 4.7, reviews: 45, enrolled: 110,
    topics: ["React Native", "Expo", "Navigation", "Push Notifications", "App Store"],
    gradient: "from-rose-500 to-pink-500",
    featured: false,
  },
  {
    id: "crs-0010-uuid",
    title: "Public Speaking Masterclass",
    description: "Communicate ideas that move people. From structuring arguments to controlling nerves, mastering body language and delivering presentations with poise and power.",
    instructor_id: "ins-005",
    cohort_id: "coh-001",
    course_type: "personal",
    is_published: true,
    created_at: "2025-11-20",
    duration: "2 weeks", lessons: 10, level: "All Levels",
    rating: 5.0, reviews: 41, enrolled: 130,
    topics: ["Storytelling", "Body Language", "Slide Design", "Q&A Handling", "Confidence"],
    gradient: "from-sky-400 to-blue-500",
    featured: false,
  },
];

// ── Config ──────────────────────────────────────────────────
export const TYPE_CONFIG = {
  development: { label: "Development",     color: "bg-blue-50 text-blue-600",     icon: <Computer className="w-3 h-3"/> },
  design:      { label: "Design",          color: "bg-violet-50 text-violet-600", icon: <Palette className="w-3 h-3"/> },
  data:        { label: "Data Science",    color: "bg-emerald-50 text-emerald-600",icon: <BarChartBigIcon className="w-3 h-3"/> },
  business:    { label: "Business",        color: "bg-amber-50 text-amber-600",   icon: <ChartLine className="w-3 h-3"/> },
  personal:    { label: "Personal Growth", color: "bg-sky-50 text-sky-600",       icon: <Sprout className="w-3 h-3"/> },
};