export const COHORTS = [
  {
    id: "a1b2c3d4-0001",
    name: "Full-Stack Web Development",
    subtitle: "From zero to full-stack developer in 12 weeks",
    start_date: "2026-04-14",
    end_date: "2026-07-07",
    enrollment_open_date: "2026-03-01",
    enrollment_close_date: "2026-04-10",
    extension_date: "2026-07-21",
    course_type: "development",
    is_active: true,
    created_at: "2026-01-15",
    featured: true,
    // UI extras
    instructor: { name: "Freddy Bijanja", role: "Lead Instructor", initials: "FB", gradient: "from-blue-500 to-cyan-400" },
    seats: 24, seatsLeft: 6,
    rating: 4.9, reviews: 148,
    topics: ["HTML & CSS", "JavaScript", "React", "Node.js", "Databases"],
    sessions: "3x / week",
    level: "Beginner",
    gradient: "from-blue-600 to-cyan-500",
  },
  {
    id: "a1b2c3d4-0002",
    name: "UI/UX Design Mastery",
    subtitle: "Design beautiful products people love to use",
    start_date: "2026-04-21",
    end_date: "2026-06-16",
    enrollment_open_date: "2026-03-10",
    enrollment_close_date: "2026-04-18",
    extension_date: "2026-06-23",
    course_type: "design",
    is_active: true,
    created_at: "2026-01-20",
    featured: false,
    instructor: { name: "IRADUKUNDA Boris", role: "Design Lead", initials: "IB", gradient: "from-violet-500 to-pink-400" },
    seats: 20, seatsLeft: 12,
    rating: 4.8, reviews: 93,
    topics: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
    sessions: "2x / week",
    level: "All Levels",
    gradient: "from-violet-500 to-pink-500",
  },
  {
    id: "a1b2c3d4-0003",
    name: "Data Science & Analytics",
    subtitle: "Turn raw data into actionable insights",
    start_date: "2026-02-03",
    end_date: "2026-04-14",
    enrollment_open_date: "2026-01-05",
    enrollment_close_date: "2026-01-30",
    extension_date: "2026-04-28",
    course_type: "data",
    is_active: true,
    created_at: "2025-12-01",
    featured: false,
    instructor: { name: "Olivier Nduwayesu", role: "Data Engineer", initials: "ON", gradient: "from-emerald-500 to-teal-400" },
    seats: 18, seatsLeft: 0,
    rating: 4.9, reviews: 76,
    topics: ["Python", "Pandas", "SQL", "Visualization", "ML Basics"],
    sessions: "2x / week",
    level: "Intermediate",
    gradient: "from-emerald-500 to-teal-400",
  },
  {
    id: "a1b2c3d4-0004",
    name: "Digital Marketing Strategy",
    subtitle: "Build and scale brands in the digital age",
    start_date: "2026-05-05",
    end_date: "2026-06-16",
    enrollment_open_date: "2026-04-01",
    enrollment_close_date: "2026-05-01",
    extension_date: "2026-06-23",
    course_type: "business",
    is_active: false,
    created_at: "2026-02-10",
    featured: false,
    instructor: { name: "Sarah Amara", role: "Marketing Expert", initials: "SA", gradient: "from-amber-400 to-orange-400" },
    seats: 30, seatsLeft: 30,
    rating: null, reviews: 0,
    topics: ["SEO", "Content Strategy", "Paid Ads", "Analytics", "Social Media"],
    sessions: "2x / week",
    level: "All Levels",
    gradient: "from-amber-400 to-orange-400",
  },
  {
    id: "a1b2c3d4-0005",
    name: "Mobile App Development",
    subtitle: "Ship iOS and Android apps with React Native",
    start_date: "2026-04-28",
    end_date: "2026-07-07",
    enrollment_open_date: "2026-03-15",
    enrollment_close_date: "2026-04-24",
    extension_date: "2026-07-14",
    course_type: "development",
    is_active: true,
    created_at: "2026-01-28",
    featured: false,
    instructor: { name: "Freddy Bijanja", role: "Lead Instructor", initials: "FB", gradient: "from-blue-500 to-cyan-400" },
    seats: 15, seatsLeft: 3,
    rating: 4.7, reviews: 54,
    topics: ["React Native", "Expo", "Navigation", "APIs", "App Store"],
    sessions: "2x / week",
    level: "Intermediate",
    gradient: "from-rose-500 to-pink-500",
  },
  {
    id: "a1b2c3d4-0006",
    name: "Public Speaking & Communication",
    subtitle: "Communicate with confidence and clarity",
    start_date: "2026-01-06",
    end_date: "2026-02-03",
    enrollment_open_date: "2025-12-01",
    enrollment_close_date: "2026-01-03",
    extension_date: "2026-02-10",
    course_type: "personal",
    is_active: false,
    created_at: "2025-11-15",
    featured: false,
    instructor: { name: "Amara Diallo", role: "Coach", initials: "AD", gradient: "from-sky-400 to-blue-400" },
    seats: 25, seatsLeft: 0,
    rating: 5.0, reviews: 41,
    topics: ["Storytelling", "Presentations", "Body Language", "Persuasion"],
    sessions: "2x / week",
    level: "All Levels",
    gradient: "from-sky-400 to-blue-500",
  },
];